server:
    port: 9099
spring:
    application:
        name: spring.custom.error
    datasource:
        driverClassName: org.h2.Driver
        password: ''
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
